# Generated by Django 6.0.4 on 2026-07-25 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('v1', '0005_user_user_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='enquiry',
            name='customer_type',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
