# Generated by Django 6.0.4 on 2026-09-27 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('v1', '0006_enquiry_customer_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(max_length=2, unique=True)),
                ('name', models.CharField(default=None, max_length=100, null=True)),
            ],
            options={
                'verbose_name': 'country',
                'db_table': 'country',
            },
        ),
        migrations.AddField(
            model_name='materials',
            name='blocked_countries',
            field=models.ManyToManyField(blank=True, related_name='blocked_materials', to='v1.country'),
        ),
    ]
